---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "webfrontend-secrets"
  labels:
    app.kubernetes.io/name: "aspireapp2-apphost"
    app.kubernetes.io/component: "webfrontend"
    app.kubernetes.io/instance: "{{.Release.Name}}"
stringData:
  ConnectionStrings__cache: "192.168.1.106:6379"
  CACHE_URI: "redis://:192.168.1.106:6379"
type: "Opaque"
